# Generated by Django 3.1.7 on 2021-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210417_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveseller',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
