# Generated by Django 3.1.7 on 2021-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210408_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
