# Generated by Django 3.1.7 on 2021-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210408_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_stock',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
